# Generated by Django 5.0.4 on 2024-06-04 04:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default='', verbose_name='cart id')),
                ('product_id', models.IntegerField(default='', verbose_name='product id')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_id', models.IntegerField(default='', verbose_name='id')),
                ('collection_name', models.CharField(default='', max_length=50, verbose_name='name')),
                ('user_id', models.IntegerField(default='', verbose_name='user id')),
                ('product_id', models.IntegerField(default='', verbose_name='product id')),
            ],
        ),
        migrations.CreateModel(
            name='HDD',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('hdd_type', models.CharField(default='', max_length=50)),
                ('series', models.CharField(max_length=100)),
                ('capacity', models.CharField(default='', max_length=50)),
                ('memory', models.IntegerField()),
                ('model', models.CharField(max_length=100)),
                ('RPM', models.IntegerField()),
                ('warranty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default='', verbose_name='id')),
                ('user_id', models.IntegerField(default='', verbose_name='user id')),
                ('amount', models.IntegerField(default=0, verbose_name='total price')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='time')),
                ('submitted', models.BooleanField(default=False, verbose_name='if the order has been submitted')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default='', verbose_name='id')),
                ('product_id', models.IntegerField(default='', verbose_name='product id')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('price', models.IntegerField(default='', verbose_name='price')),
                ('brand', models.CharField(default='', max_length=30, verbose_name='brand')),
                ('original_info', models.CharField(max_length=200)),
                ('left', models.IntegerField(default=1000, verbose_name='left')),
                ('product_type', models.CharField(default='', max_length=10, verbose_name='RAMorHDDorSSD')),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('ram_type', models.CharField(default='', max_length=50)),
                ('ddr_gen', models.CharField(max_length=100)),
                ('channel', models.CharField(max_length=100)),
                ('capacity', models.CharField(default='', max_length=50)),
                ('clock_rate', models.IntegerField()),
                ('remark', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SSD',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('ssd_type', models.CharField(default='', max_length=50)),
                ('capacity', models.CharField(default='', max_length=50)),
                ('read_speed', models.IntegerField()),
                ('write_speed', models.IntegerField()),
                ('warranty', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(default='', primary_key=True, serialize=False, verbose_name='id')),
                ('user_name', models.CharField(default='', max_length=30, verbose_name='name')),
                ('password', models.CharField(default='', max_length=30, verbose_name='password')),
            ],
        ),
    ]
